### ISSUE TITLE
Feat:Want to enhance Ui of NAvbar in mobile page

### ISSUE THREAD

**Issue by nishant0708** [Anushkabh/krishiconnect#611]
### Describe the feature

Currently we can't see navabar in mobile screen i want to fix that

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/101548649/cbdaed4a-6ccc-49fa-90b6-3431db2e7bd0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.

**Comment by himanshu-03** [comment]
Hello @nishant0708 !

Do let me know how you are planning to change this.

**Comment by nishant0708** [comment]
No no it is fixed now

**Comment by himanshu-03** [comment]
I dont see it fixed

**Comment by himanshu-03** [comment]
![image](https://github.com/Anushkabh/krishiconnect/assets/97957777/156f5b94-2e35-49a7-ab0e-874780ab4b55)

Once you hover down and come  up the issue still remains. @nishant0708

**Comment by nishant0708** [comment]
Oo okay actually I thought someone fixed it no worries I
Will do it

**Comment by nishant0708** [comment]
I will @himanshu-03 raise pr of this and of contact us page by tomorrow

**Comment by nishant0708** [comment]
> Hello @nishant0708 !
> 
> Do let me know how you are planning to change this.
@himanshu-03  I was thinking something Like this 

https://github.com/Anushkabh/krishiconnect/assets/101548649/3734ce3c-2d32-49f1-85eb-6d021a4b47ca

**Comment by himanshu-03** [comment]
> > Hello @nishant0708 !
> > Do let me know how you are planning to change this.
> > @himanshu-03  I was thinking something Like this
> 
>  krishi-navbar.mp4

This lookss good but if the whole content too shifts downwards wont it look more good?

**Comment by himanshu-03** [comment]
I am assigninig you this issue @nishant0708

**Comment by nishant0708** [comment]
@himanshu-03 I will make both and let you decide which one you want how about that?

**Comment by himanshu-03** [comment]
> @himanshu-03 I will make both and let you decide which one you want how about that?

Nah work on the one I am saying make the contnt go downward when we click oon the nav

**Comment by nishant0708** [comment]
hey @himanshu-03  can you see this so that i could start applying same logic to all other page if it looks good to you
https://github.com/Anushkabh/krishiconnect/assets/101548649/ba18f5dc-7f2d-4668-b465-b09424762ac0

**Comment by himanshu-03** [comment]
> hey @himanshu-03 can you see this so that i could start applying same logic to all other page if it looks good to you https://github.com/Anushkabh/krishiconnect/assets/101548649/ba18f5dc-7f2d-4668-b465-b09424762ac0

Thats great

**Comment by nishant0708** [comment]
@himanshu-03  I have raised pr please check it

**Comment by himanshu-03** [comment]
Why have you created two PR's?
